In [16]:
from geometry import SO3, SE3, SO2, SE2
import numpy as np
import symforce.symbolic as sf

## SO(2) Conventions

They seem identical!

In [17]:
def geometryToSymforceRot2(q):
    return sf.Rot2.from_angle(q.angle())

In [18]:
q1 = SO2.random()
R1 = geometryToSymforceRot2(q1)
q2 = SO2.random()
R2 = geometryToSymforceRot2(q2)

In [19]:
q2 - q1

array([1.24099941])

In [20]:
R1.local_coordinates(R2)

[atan2(0.946108131878466, 0.32385089592811)]

In [22]:
np.arctan2(0.946108131878466, 0.32385089592811)

1.2409994105016053

In [23]:
q1

SO(2): [ 0.483425, -0.875386i ]

In [24]:
R1

<Rot2 <C real=0.48342459747263, imag=-0.875386005461834>>

## SE(2) Conventions

- **geometry:** translation first, then rotation
- **symforce:** rotation first, then transform
- Representation ordering differences mirror tangent space ordering differences
- ***Symforce doesn't scale the translation by the left Jacobian...***

In [27]:
def geometryToSymforceTrans2(T):
    t = T.t()
    q = T.q()
    return sf.Pose2(R=sf.Rot2.from_angle(q.angle()), t=sf.V2(t))

In [28]:
T1 = SE2.random()
X1 = geometryToSymforceTrans2(T1)
T2 = SE2.random()
X2 = geometryToSymforceTrans2(T2)

In [29]:
T2 - T1

array([-0.34419452,  0.93742488, -0.88294329])

In [31]:
X1.local_coordinates(X2)

[atan2(-0.772610861391239, 0.634879875929524),
 -0.486860466416395,
 -0.834910978020593]

## SO(3) Conventions

- **geometry:** **w**, x, y, z
- **symforce:** x, y, z, **w**
- Despite difference in representation ordering, tangent space ordering is *identical*

In [2]:
def geometryToSymforceRotation(q):
    rpy = q.toEuler()
    return sf.Rot3.from_yaw_pitch_roll(rpy[2], rpy[1], rpy[0])

In [3]:
q1 = SO3.random()
R1 = geometryToSymforceRotation(q1)
q2 = SO3.random()
R2 = geometryToSymforceRotation(q2)

In [4]:
q2 - q1

array([-0.8022592 ,  1.77019986, -1.86321679])

In [5]:
R1.local_coordinates(R2)

[-0.80225920297874, 1.77019986313989, -1.86321678724983]

In [6]:
R1

<Rot3 <Q xyzw=[-0.683192728724483, 0.716827827300218, -0.0710432118093974, 0.119826639282961]>>

## SE(3) Conventions

- **geometry:** translation first, then rotation
- **symforce:** rotation first, then transform
- Representation ordering differences mirror tangent space ordering differences
- ***Symforce doesn't scale the translation by the left Jacobian...***

In [7]:
def geometryToSymforceTransform(T):
    t = T.t()
    q = T.q()
    return sf.Pose3(R=sf.Rot3.from_rotation_matrix(q.R()), t=sf.V3(t))

In [8]:
T1 = SE3.random()
X1 = geometryToSymforceTransform(T1)
T2 = SE3.random()
X2 = geometryToSymforceTransform(T2)

In [9]:
T2 - T1

array([-0.98348644, -0.79402169,  0.61584166, -0.89854147,  2.3093438 ,
       -0.01905432])

In [13]:
T2

SE(3): [ -0.198111i, -0.740419j, -0.782382k ] [ 0.749209, -0.423079i, 0.019420j, 0.509227k ]

In [14]:
T1

SE(3): [ -0.716795i, 0.213938j, -0.967399k ] [ 0.402477, 0.567866i, -0.476148j, 0.537423k ]

In [15]:
T2.t() - T1.t()

array([ 0.51868368, -0.95435686,  0.18501646])

In [12]:
X1.local_coordinates(X2)

[-0.898541467169147,
 2.30934379535911,
 -0.0190543242188678,
 0.51868367778076,
 -0.954356858951206,
 0.185016460802879]

In [38]:
X1

<Pose3 R=<Rot3 <Q xyzw=[-0.623511218461162, 0.241437925601021, 0.696364345368465, -0.260802965922747]>>, t=(0.0519907004442022, -0.827888304287516, -0.615572308011154)>

## Jacobian Conversion Rules