# Intro to NumPy

**Source:** https://labs.acme.byu.edu/PythonEssentials/NumpyIntro/NumpyIntro.html

Writing efficient numerical code starts with the right data structure, and in Python, that means NumPy. This lab covers creating, slicing, and performing operations on NumPy arrays with emphasis on vectorized computation.

In [1]:
import numpy as np


## 1. NumPy Array Fundamentals

The `ndarray` is NumPy's core object. Arrays use comma-separated indices for multi-dimensional access.

In [2]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A[0, 1])   # 2
print(A.shape)   # (2, 3)

print(A.dtype)   # int64
print(A.ndim)    # 2
print(A.size)    # 6

2
(2, 3)
int64
2
6


## 2. Array Creation

In [3]:
print(np.zeros(5))
print(np.ones((2, 5)))

print(np.eye(3))
print(np.arange(10))
print(np.full((2, 3), 7))

[0. 0. 0. 0. 0.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 1 2 3 4 5 6 7 8 9]
[[7 7 7]
 [7 7 7]]


## 3. Basic Operations

NumPy arrays support element-wise arithmetic. Matrix multiplication uses `@` or `np.dot()`.

In [4]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(x + y)   # [5 7 9]
print(x * y)   # [4 10 18]


A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(A @ B)

[5 7 9]
[ 4 10 18]
[[19 22]
 [43 50]]


## 4. Slicing and Fancy Indexing

In [5]:
x = np.arange(10)
print(x[3:8])           # elements 3-7
print(x[:3])            # first 3
print(x[::2])           # every other


idx = np.array([3, 1, 4])
print(x[idx])           # fancy indexing
print(x[x > 5])         # boolean mask

[3 4 5 6 7]
[0 1 2]
[0 2 4 6 8]
[3 1 4]
[6 7 8 9]


## 5. Reshaping and Stacking

In [6]:
A = np.arange(12)
print(A.reshape((3, 4)))
print(A.reshape((2, -1)))
print(np.ravel(A))


a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.vstack([a, b]))
print(np.hstack([a, b]))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


## 6. Broadcasting

In [7]:
A = np.arange(12).reshape((4, 3))
x = np.arange(3)

print(A + x)  # x added to each row

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


## 7. Universal Functions and Aggregation Methods

In [8]:
x = np.array([-3, 1, 4, -1, 5, 9])
print(np.abs(x))
print(np.sqrt(np.abs(x)))


A = np.arange(12).reshape((3, 4))
print(A.sum())           # total sum
print(A.sum(axis=0))     # column sums
print(A.sum(axis=1))     # row sums
print(A.mean(axis=1))

[3 1 4 1 5 9]
[1.73205081 1.         2.         1.         2.23606798 3.        ]
66
[12 15 18 21]
[ 6 22 38]
[1.5 5.5 9.5]


---

## Problem 1: Matrix Multiplication

Define A (2×3) and B (3×4) and return the matrix product AB.

In [9]:
def prob1():
    A = np.array([[3, -1, 4],
                  [1,  5, -9]])
    B = np.array([[2,  6, -5,  3],
                  [5, -8,  9,  7],
                  
                  [9, -3, -2, -3]])
    return A @ B

print(prob1())

[[ 37  14 -32 -10]
 [-54  -7  58  65]]


## Problem 2: Polynomial Matrix Expression

Define A (3×3) and return −A³ + 9A² − 15A (matrix powers).

In [10]:
def prob2():
    A = np.array([[ 3, 1, 4],
                  [ 1, 5, 9],
                  [-5, 3, 1]])
    A2 = A @ A
    
    A3 = A2 @ A
    return -A3 + 9*A2 - 15*A

print(prob2())

[[0 0 0]
 [0 0 0]
 [0 0 0]]


## Problem 3: Array Construction

Create A (7×7 upper triangular, 1s on/above diagonal) and B (−1s on/below, 5s above). Return ABA as `np.int64`.

In [11]:
def prob3():
    A = np.triu(np.ones((7, 7)))
    B = np.tril(-np.ones((7, 7))) + np.triu(5*np.ones((7, 7)), k=1)
    return (A @ B @ A).astype(np.int64)
    

print(prob3())

[[ -7  -8  -3   8  25  48  77]
 [ -6 -12 -12  -6   6  24  48]
 [ -5 -10 -15 -14  -7   6  25]
 [ -4  -8 -12 -16 -14  -6   8]
 [ -3  -6  -9 -12 -15 -12  -3]
 [ -2  -4  -6  -8 -10 -12  -8]
 [ -1  -2  -3  -4  -5  -6  -7]]


## Problem 4: Fancy Indexing — Zero Out Negatives

In [12]:
def prob4(A):
    B = A.copy()
    B[B < 0] = 0
    return B

test = np.array([-3, 1, -4, 1, 5, -9, 2, 6])

print(prob4(test))

[0 1 0 1 5 0 2 6]


## Problem 5: Block Matrix Construction

Build the 9×9 block matrix:
```
[ 0    A^T   I  ]
[ A    0     0  ]
[ B    0     C  ]
```

In [18]:
def prob5():
    A = np.array([[0, 2, 4],
                  [1, 3, 5]])
    B = np.array([[3, 0, 0],
                  [3, 3, 0],
                  [3, 3, 3]])
    C = -2 * np.eye(3)
    I = np.eye(3)

    row1 = np.hstack([np.zeros((3, 3)), A.T,           I             , np.zeros((3, 1))
                     ])
    # print(row1)
    row2 = np.hstack([A,                np.zeros((2, 3)), np.zeros((2, 3))])
    # print(row2)
    row3 = np.hstack([B,                np.zeros((3, 3)), C             ])
    # print(row3)

    return np.vstack([row1, row2, row3])



M = prob5()

print(M.shape)  # (9, 9)
print(M)

(8, 9)
[[ 0.  0.  0.  0.  1.  1.  0.  0.  0.]
 [ 0.  0.  0.  2.  3.  0.  1.  0.  0.]
 [ 0.  0.  0.  4.  5.  0.  0.  1.  0.]
 [ 0.  2.  4.  0.  0.  0.  0.  0.  0.]
 [ 1.  3.  5.  0.  0.  0.  0.  0.  0.]
 [ 3.  0.  0.  0.  0.  0. -2. -0. -0.]
 [ 3.  3.  0.  0.  0.  0. -0. -2. -0.]
 [ 3.  3.  3.  0.  0.  0. -0. -0. -2.]]


## Problem 6: Row-Stochastic Matrix

In [14]:
def prob6(A):
    return A / A.sum(axis=1, keepdims=True)

M = np.array([[1, 2, 3],
              [4, 5, 6],
              
              [7, 8, 9]], dtype=float)
result = prob6(M)
print(result)
print(result.sum(axis=1))  # all 1.0

[[0.16666667 0.33333333 0.5       ]
 [0.26666667 0.33333333 0.4       ]
 [0.29166667 0.33333333 0.375     ]]
[1. 1. 1.]


## Problem 7: Greatest Product of Four Adjacent Numbers

Find the greatest product of four adjacent numbers in any direction in a 20×20 grid.

In [15]:
grid = np.array([
    [ 8,  2, 22, 97, 38, 15,  0, 40,  0, 75,  4,  5,  7, 78, 52, 12, 50, 77, 91,  8],
    [49, 49, 99, 40, 17, 81, 18, 57, 60, 87, 17, 40, 98, 43, 69, 48,  4, 56, 62,  0],
    [81, 49, 31, 73, 55, 79, 14, 29, 93, 71, 40, 67, 53, 88, 30,  3, 49, 13, 36, 65],
    [52, 70, 95, 23,  4, 60, 11, 42, 69, 24, 68, 56,  1, 32, 56, 71, 37,  2, 36, 91],
    [22, 31, 16, 71, 51, 67, 63, 89, 41, 92, 36, 54, 22, 40, 40, 28, 66, 33, 13, 80],
    [24, 47, 32, 60, 99,  3, 45,  2, 44, 75, 33, 53, 78, 36, 84, 20, 35, 17, 12, 50],
    [32, 98, 81, 28, 64, 23, 67, 10, 26, 38, 40, 67, 59, 54, 70, 66, 18, 38, 64, 70],
    [67, 26, 20, 68,  2, 62, 12, 20, 95, 63, 94, 39, 63,  8, 40, 91, 66, 49, 94, 21],
    [24, 55, 58,  5, 66, 73, 99, 26, 97, 17, 78, 78, 96, 83, 14, 88, 34, 89, 63, 
     72],
    [21, 36, 23,  9, 75,  0, 76, 44, 20, 45, 35, 14,  0, 61, 33, 97, 34, 31, 33, 95],
    [78, 17, 53, 28, 22, 75, 31, 67, 15, 94,  3, 80,  4, 62, 16, 14,  9, 53, 56, 92],
    [16, 39,  5, 42, 96, 35, 31, 47, 55, 58, 88, 24,  0, 17, 54, 24, 36, 29, 85, 57],
    [86, 56,  0, 48, 35, 71, 89,  7,  5, 44, 44, 37, 44, 60, 21, 58, 51, 54, 17, 58],
    [19, 80, 81, 68,  5, 94, 47, 69, 28, 73, 92, 13, 86, 52, 17, 77,  4, 89, 55, 40],
    [ 4, 52,  8, 83, 97, 35, 99, 16,  7, 97, 57, 32, 16, 26, 26, 79, 33, 27, 98, 66],
    [88, 36, 68, 87, 57, 62, 20, 72,  3, 46, 33, 67, 46, 55, 12, 32, 63, 93, 53, 69],
    [ 4, 42, 16, 73, 38, 25, 39, 11, 24, 94, 72, 18,  8, 46, 29, 32, 40, 62, 76, 36],
    [20, 69, 36, 41, 72, 30, 23, 88, 34, 62, 99, 69, 82, 67, 59, 85, 74,  4, 36, 16],
    [20, 73, 35, 29, 78, 31, 90,  1, 74, 31, 49, 71, 48, 86, 81, 16, 23, 57,  5, 54],
    [ 1, 70, 54, 71, 83, 51, 54, 69, 16, 92, 33, 48, 61, 43, 52,  1, 89, 19, 67, 48]
])

def prob7(grid):
    horiz = np.max(grid[:, :-3] * grid[:, 1:-2] * grid[:, 2:-1] * grid[:, 3:])
    vert  = np.max(grid[:-3, :] * grid[1:-2, :] * grid[2:-1, :] * grid[3:, :])
    diag1 = np.max(grid[:-3, :-3] * grid[1:-2, 1:-2] * grid[2:-1, 2:-1] * grid[3:, 3:])
    diag2 = np.max(grid[:-3, 3:] * grid[1:-2, 2:-1] * grid[2:-1, 1:-2] * grid[3:, :-3])
    return int(max(horiz, vert, diag1, diag2))

print(prob7(grid))  # 70600674

70600674
